apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminservice
  template:
    metadata:
      labels:
        app: adminservice
    spec:
      containers:
        - name: adminservice
          image: abelofficial/adminservice:latest
